### ISSUE TITLE
Create endpoint for profile request.

### ISSUE THREAD

**Issue by gfabrizio** [gfabricio/gravtr#1]
More details about: https://pt.gravatar.com/site/implement/profiles/

**Comment by bwhaston** [comment]
Hi! I'd like to contribute to your up-for-grabs contribution. I'd like clarification, though. What do you mean by "endpoint?" I looked at the link you posted above, and I didn't feel like it shed much light on the issue. I've read the developer docs for Gravatar, and they didn't really help with this, either.

**Comment by gfabrizio** [comment]
Hello @PDFormat , I'm closing this Issue, this one don't make sense. I'll try to create a more detailed list of enhancements during the weekend. Sorry for waste your time.
